{
 "title": "Synthetic Web Monitoring",
 "tags": [
  "synthetic",
  "webperf"
 ],
 "refresh": "1m",
 "panels": [
  {
   "title": "BBC TTI & Full Load",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"<web_metrics>\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"https://www.bbc.co.uk\" and (r._field == \"time_to_interactive\" or r._field == \"time_to_full_load\"))"
    }
   ]
  },
  {
   "title": "Google TTI & Full Load",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"<web_metrics>\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"https://www.google.co.uk\" and (r._field == \"time_to_interactive\" or r._field == \"time_to_full_load\"))"
    }
   ]
  },
  {
   "title": "Sky TTI & Full Load",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"<web_metrics>\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"https://www.sky.co.uk\" and (r._field == \"time_to_interactive\" or r._field == \"time_to_full_load\"))"
    }
   ]
  },
  {
   "title": "Overall TTI & Full Load",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"<web_metrics>\") |> range(start: -1h) |> filter(fn: (r) => r._measurement =~ /bbc|google|sky/ and (r._field == \"time_to_interactive\" or r._field == \"time_to_full_load\"))"
    }
   ]
  }
 ]
}